# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0.1 on 2026-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="class_type",
            field=models.CharField(
                choices=[("ONE_ON_ONE", "One-on-One Class"), ("GROUP", "Group Class")],
                default="ONE_ON_ONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="days_per_week",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_days",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated days e.g. Monday, Wednesday",
                max_length=200,
                null=True,
            ),
        ),
    ]
