# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-01-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentprofile_class_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="hours_per_week",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Hours per session",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Unique payment reference",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total calculated fee",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PAID", "Paid"),
                    ("PARTIAL", "Partial"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
