# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-01-20 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentprofile_hours_per_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="admission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="wallet_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Current available funds for classes",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Unique payment reference for initial fee",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total calculated first payment amount",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("DEDUCTION", "Class Deduction"),
                            ("FEE", "One-Time Fee"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
    ]
