# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-01-29 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_studentprofile_admission_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="assigned_tutor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TUTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="meeting_link",
            field=models.URLField(
                blank=True, help_text="Zoom/Meet link for classes", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="meeting_link_approved",
            field=models.BooleanField(
                default=True, help_text="If tutor sets link, admin must approve"
            ),
        ),
    ]
