# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_studentprofile_assigned_tutor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_time_exact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
