# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "__first__"),
        ("students", "0006_studentprofile_preferred_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="enrolled_course",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="enrolled_courses",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_students", to="programs.subject"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                    ("JAMB", "JAMB"),
                    ("WAEC", "WAEC"),
                    ("NECO", "NECO"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_mode",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("PHYSICAL", "Physical")],
                default="ONLINE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
