# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_remove_studentprofile_enrolled_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="enrolled_course",
            field=models.CharField(
                blank=True, default="General Studies", max_length=200, null=True
            ),
        ),
    ]
