# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_studentprofile_enrolled_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_tutor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TUTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
