# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_studentprofile_preferred_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="whiteboard_link",
            field=models.URLField(
                blank=True,
                help_text="Excalidraw/Whiteboard link for classes",
                null=True,
            ),
        ),
    ]
