# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="preferred_days",
            field=models.CharField(
                blank=True,
                help_text="e.g. Monday, Wednesday",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="preferred_time",
            field=models.CharField(
                blank=True, help_text="e.g. 10:00 AM", max_length=50, null=True
            ),
        ),
    ]
