# Generated by Django 6.0 on 2026-03-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_enrollment_preferred_days_enrollment_preferred_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="wallet_balance",
        ),
        migrations.DeleteModel(
            name="WalletTransaction",
        ),
    ]
