# Generated by Django 6.0 on 2026-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_remove_studentprofile_wallet_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="preferred_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="schedule",
            field=models.TextField(
                blank=True, help_text="JSON list of {day, time} objects", null=True
            ),
        ),
    ]
