# Generated by Django 6.0 on 2026-04-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_enrollment_preferred_start_date_enrollment_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="target_exam_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JAMB", "JAMB"),
                    ("WAEC", "WAEC"),
                    ("NECO", "NECO"),
                    ("BECE", "BECE"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="target_exam_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                    ("JUNIOR_WAEC", "Junior WAEC (BECE)"),
                    ("JAMB", "JAMB"),
                    ("WAEC", "WAEC"),
                    ("NECO", "NECO"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
