# Generated by Django 6.0.1 on 2026-04-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_studentprofile_target_exam_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="relationship",
            field=models.CharField(
                blank=True,
                help_text="Relationship to parent (e.g. Mother, Father)",
                max_length=50,
                null=True,
            ),
        ),
    ]
