# Generated by Django 6.0 on 2026-04-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_studentprofile_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(
                blank=True, help_text="Full residential address", null=True
            ),
        ),
    ]
