# Generated by Django 6.0.1 on 2026-04-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_studentprofile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                    ("JUNIOR_WAEC", "Junior WAEC (BECE)"),
                    ("JAMB", "JAMB"),
                    ("WAEC", "WAEC"),
                    ("NECO", "NECO"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Unique payment reference for initial fee",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="preferred_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="preferred_time_exact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="relationship",
            field=models.CharField(
                blank=True,
                help_text="Relationship to parent (e.g. Mother, Father)",
                max_length=255,
                null=True,
            ),
        ),
    ]
