# Generated by Django 6.0.1 on 2026-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_alter_studentprofile_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="hours_per_week",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Hours per class session",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total calculated registration/first month fee",
                max_digits=10,
            ),
        ),
    ]
