# Generated by Django 6.0.1 on 2026-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_studentprofile_hours_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIAL', 'Partial')], db_index=True, default='UNPAID', max_length=20),
        ),
    ]
