# Generated by Django 6.0.1 on 2026-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_alter_studentprofile_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                    ("JUNIOR_WAEC", "Junior WAEC (BECE)"),
                    ("JAMB", "JAMB"),
                    ("WAEC", "WAEC"),
                    ("NECO", "NECO"),
                    ("ADULT", "Adult"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
