# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="admin_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Default admin commission (%) for this subject",
                max_digits=5,
            ),
        ),
    ]
