# Generated by Django 6.0.1 on 2026-05-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whiteboard", "0002_savedwhiteboard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livewhiteboardsession",
            old_name="jitsi_room_id",
            new_name="room_id",
        ),
    ]
