# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("JAMB", "JAMB"),
                    ("WAEC", "WAEC"),
                    ("NECO", "NECO"),
                    ("JSSCE", "JSSCE"),
                    ("PRIMARY", "Common Entrance (Primary)"),
                    ("INTERNAL", "Internal Assessment"),
                ],
                max_length=20,
            ),
        ),
    ]
