# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0.1 on 2026-01-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialapplication",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trialapplication",
            name="course_interested",
            field=models.CharField(default="Quranic Recitation", max_length=200),
        ),
        migrations.AddField(
            model_name="trialapplication",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trialapplication",
            name="preferred_day",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trialapplication",
            name="preferred_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trialapplication",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
