# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0.1 on 2026-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_trialapplication_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialapplication",
            name="assigned_tutor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trialapplication",
            name="duration",
            field=models.IntegerField(default=40, help_text="Duration in minutes"),
        ),
        migrations.AddField(
            model_name="trialapplication",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
