# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0.1 on 2026-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_trialapplication_assigned_tutor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialapplication",
            name="preferred_time_exact",
            field=models.CharField(
                blank=True, help_text="Specific time if known", max_length=50, null=True
            ),
        ),
    ]
