# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0.1 on 2026-01-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_trialapplication_preferred_time_exact"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialapplication",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
