# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0.1 on 2026-01-16 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_trialapplication_reminder_sent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trialapplication",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_trials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
