# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_trialapplication_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoomclass",
            name="whiteboard_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
