# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_zoomclass_whiteboard_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialapplication",
            name="preferred_tutor",
            field=models.CharField(
                blank=True,
                help_text="Tutor chosen by user during request",
                max_length=200,
                null=True,
            ),
        ),
    ]
