# Generated by Django 6.0 on 2026-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_trialapplication_preferred_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialapplication",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
    ]
