# Generated by Django 6.0 on 2026-03-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_options_transaction_wallet_withdrawal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeeType",
        ),
    ]
