# Generated by Django 6.0.1 on 2026-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_platformsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("PAYSTACK", "Paystack"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("WALLET", "Wallet Balance"),
                ],
                max_length=20,
            ),
        ),
    ]
