# Generated by Django 6.0 on 2026-03-29 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="learningmaterial",
            name="assigned_student",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only this student can see this material",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
