# Generated by Django 6.0 on 2026-03-29 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_learningmaterial_assigned_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaterial',
            name='assigned_student',
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='If set, only these students can see this material', related_name='assigned_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
