# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("JAMB", "JAMB"), ("WAEC", "WAEC"), ("NECO", "NECO")],
                        max_length=20,
                    ),
                ),
                (
                    "year_range",
                    models.CharField(help_text="e.g. 2010-2023", max_length=50),
                ),
                (
                    "content",
                    models.JSONField(help_text="Generated questions in JSON format"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.subject",
                    ),
                ),
            ],
        ),
    ]
