# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledsession",
            name="duration",
            field=models.IntegerField(default=40, help_text="Duration in minutes"),
        ),
    ]
