# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_scheduledsession_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledsession",
            name="whiteboard_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WhiteboardSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_image",
                    models.ImageField(blank=True, null=True, upload_to="whiteboards/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_sessions",
                        to="classes.scheduledsession",
                    ),
                ),
            ],
        ),
    ]
