# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-03-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_scheduledsession_whiteboard_link_whiteboardsession"),
        ("programs", "0002_subject_admin_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledsession",
            name="admin_percentage_at_completion",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="scheduledsession",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="scheduledsession",
            name="completion_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledsession",
            name="fee_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="scheduledsession",
            name="payout_status",
            field=models.CharField(
                choices=[
                    ("NONE", "Not Applicable"),
                    ("PENDING", "Pending Release"),
                    ("RELEASED", "Released to Tutor"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scheduledsession",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_sessions",
                to="programs.subject",
            ),
        ),
    ]
