# Generated by Django 6.0 on 2026-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_scheduledsession_admin_percentage_at_completion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledsession",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
    ]
