# Generated by Django 6.0 on 2026-03-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_trialapplication_is_started"),
        ("classes", "0006_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="reschedulerequest",
            name="trial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reschedule_requests",
                to="applications.trialapplication",
            ),
        ),
        migrations.AlterField(
            model_name="reschedulerequest",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reschedule_requests",
                to="classes.scheduledsession",
            ),
        ),
    ]
