# Generated by Django 6.0 on 2026-03-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_reschedulerequest_trial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="hours_per_week",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="preferred_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="schedule",
            field=models.TextField(
                blank=True, help_text="JSON list of {day, time} objects", null=True
            ),
        ),
    ]
