# Generated by Django 6.0 on 2026-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classes",
            "0008_booking_hours_per_week_booking_preferred_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="class_structure",
            field=models.CharField(
                blank=True, default="One-on-One", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="learning_level",
            field=models.CharField(
                blank=True, default="Primary School", max_length=100, null=True
            ),
        ),
    ]
