# Generated by Django 6.0 on 2026-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0009_booking_class_structure_booking_learning_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="hours_per_session",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
