# Generated by Django 6.0.1 on 2026-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_booking_hours_per_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
