# Generated by Django 6.0.1 on 2026-07-05 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_scheduledsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsession',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='scheduledsession',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
