# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-01-29 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("interview_link", models.URLField(blank=True, null=True)),
                (
                    "appointment_letter",
                    models.FileField(
                        blank=True, null=True, upload_to="appointment_letters/"
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="tutor_images/"),
                ),
                (
                    "cv_resume",
                    models.FileField(
                        blank=True, null=True, upload_to="tutor_credentials/"
                    ),
                ),
                (
                    "credentials",
                    models.FileField(
                        blank=True, null=True, upload_to="tutor_credentials/"
                    ),
                ),
                ("experience_years", models.IntegerField(default=0)),
                (
                    "subjects_to_teach",
                    models.TextField(help_text="Comma separated subjects"),
                ),
                ("languages", models.TextField(default="English")),
                ("has_online_exp", models.BooleanField(default=False)),
                ("intro_video_url", models.URLField(blank=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("COMPUTER", "Computer"),
                            ("PHONE", "Phone"),
                            ("BOTH", "Both"),
                        ],
                        default="COMPUTER",
                        max_length=20,
                    ),
                ),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Fiber, 4G, 5G",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "availability_days",
                    models.TextField(help_text="e.g. Monday, Wednesday, Friday"),
                ),
                (
                    "availability_hours",
                    models.TextField(help_text="e.g. 9 AM - 5 PM UTC"),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
