# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-01-29 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Display on public home page"
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="personal_gmail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="TutorDiscipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline_type",
                    models.CharField(
                        choices=[
                            ("WARNING", "Warning"),
                            ("QUERY", "Query Letter"),
                            ("EXPULSION", "Expulsion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "pdf_letter",
                    models.FileField(
                        blank=True, null=True, upload_to="disciplinary_letters/"
                    ),
                ),
                ("date_issued", models.DateTimeField(auto_now_add=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EARNING", "Earning"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("DEDUCTION", "Deduction"),
                            ("BONUS", "Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        help_text="For withdrawals: DAILY, WEEKLY, MONTHLY",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
