# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0002_tutorprofile_is_blocked_tutorprofile_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="intro_video",
            field=models.FileField(blank=True, null=True, upload_to="tutor_videos/"),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="short_recitation",
            field=models.FileField(
                blank=True, null=True, upload_to="tutor_recitations/"
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="intro_video_url",
            field=models.URLField(blank=True, help_text="Legacy URL field", null=True),
        ),
    ]
