# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0003_tutorprofile_intro_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="interview_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
