# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "__first__"),
        ("tutors", "0004_tutorprofile_interview_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("PHYSICAL", "Physical"),
                    ("BOTH", "Both"),
                ],
                default="ONLINE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="qualification",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="rate_per_month",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Monthly rate for standard commitment",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="tutors", to="programs.subject"
            ),
        ),
        migrations.CreateModel(
            name="TutorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="tutors.tutorprofile",
                    ),
                ),
            ],
        ),
    ]
