# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-02-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0005_tutorprofile_city_tutorprofile_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Short biography or teaching philosophy",
                null=True,
            ),
        ),
    ]
