# type: ignore
# pyre-ignore-all-errors
# pylint: skip-file
# Generated by Django 6.0 on 2026-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0006_tutorprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="live_class_link",
            field=models.URLField(
                blank=True, help_text="Permanent link for regular students", null=True
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="trial_class_link",
            field=models.URLField(
                blank=True, help_text="Permanent link for trial classes", null=True
            ),
        ),
    ]
