# Generated by Django 6.0 on 2026-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0007_tutorprofile_live_class_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="commission_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custom commission % (Override global/subject defaults)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
