# Generated by Django 6.0 on 2026-03-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0008_tutorprofile_commission_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorprofile",
            name="wallet_balance",
        ),
        migrations.DeleteModel(
            name="TutorTransaction",
        ),
    ]
