# Generated by Django 6.0 on 2026-04-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0009_remove_tutorprofile_wallet_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorprofile",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="hourly_rate",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=1500.0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="is_public",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Display on public home page"
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("PHYSICAL", "Physical"),
                    ("BOTH", "Both"),
                ],
                db_index=True,
                default="ONLINE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="rate_per_month",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0.0,
                help_text="Monthly rate for standard commitment",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="state",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="APPLIED",
                max_length=20,
            ),
        ),
    ]
