# Generated by Django 6.0.1 on 2026-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0010_alter_tutorprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorprofile",
            name="credentials",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="tutor_credentials/"
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="cv_resume",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="tutor_credentials/"
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="tutor_images/"
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="intro_video",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="tutor_videos/"
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="short_recitation",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="tutor_recitations/"
            ),
        ),
    ]
