# Generated by Django 6.0.1 on 2026-07-05 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0011_alter_tutorprofile_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.DecimalField(db_index=True, decimal_places=2, default=1500.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
